// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace fitnessBudyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115160136_UserUpdated")]
    partial class UserUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkoutExercise", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Exerciseid")
                        .HasColumnType("bigint")
                        .HasColumnName("exerciseid");

                    b.Property<int>("repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.Property<int>("sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<Guid>("workoutid")
                        .HasColumnType("uuid")
                        .HasColumnName("workoutid");

                    b.HasKey("id");

                    b.HasIndex("Exerciseid");

                    b.HasIndex("workoutid");

                    b.ToTable("workoutexercises");
                });

            modelBuilder.Entity("fitnessBudyApi.Models.Exercise", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("body_part")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_part");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("fitnessBudyApi.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("fitnessBudyApi.Models.Workout", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("userid")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("workouts");
                });

            modelBuilder.Entity("WorkoutExercise", b =>
                {
                    b.HasOne("fitnessBudyApi.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("Exerciseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fitnessBudyApi.Models.Workout", "workout")
                        .WithMany("workoutExercises")
                        .HasForeignKey("workoutid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("workout");
                });

            modelBuilder.Entity("fitnessBudyApi.Models.Workout", b =>
                {
                    b.HasOne("fitnessBudyApi.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("fitnessBudyApi.Models.Workout", b =>
                {
                    b.Navigation("workoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
